export const SNIPPET_TITLE_MAX_LENGTH = 35;
export const SNIPPET_CONTENT_MAX_LENGTH = 2000;
export const SNIPPET_TAG_MAX_LENGTH = 32;
export const SNIPPET_TAGS_TEXT_MAX_LENGTH = 512;

export const SNIPPET_TITLE_PREVIEW_MAX_LENGTH = 72;
export const SNIPPET_CONTENT_PREVIEW_MAX_LENGTH = 220;
export const SNIPPET_TAG_PREVIEW_MAX_LENGTH = 24;
